const supabaseUrl = 'https://xtgndbqirumlyrlqmfyf.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0Z25kYnFpcnVtbHlybHFtZnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODY4NzgsImV4cCI6MjA1MzU2Mjg3OH0.jvzqZyF1bHXhWFYASfQnc-t3PsxlASpm0WlrOh3sLBo'
const supabasePro = supabase.createClient(supabaseUrl, supabaseKey)
console.log(supabasePro);

export default supabasePro;